### ISSUE TITLE
Let's plug this into GitLab.

### ISSUE THREAD

**Issue by cirosantilli** [sharelatex/github-latex-ci#1]
I wanna plug a CI like this on GitLab, activate it by default on new projects, have side by side preview on the editor like Sharelatex, and upload the PDFs to releases whenever a release (tag) is created: https://github.com/booktree/booktree, like Travis currently can do: http://docs.travis-ci.com/user/deployment/releases/

Also consider https://github.com/philschatz/pdf-ci

**Comment by Hubbitus** [comment]
I implement it using image https://hub.docker.com/r/hubbitus/latex/ . 3 lines of code. Seams pretty cool. Is it require anything special handling than other builders?

**Comment by sductor** [comment]
@Hubbitus 
I'm really interested in sharelatex gitlab integration.
Would you please mind provide more information about your solution?
