### ISSUE TITLE
Cannot remove project

### ISSUE THREAD

**Issue by szymtor** [sharelatex/github-latex-ci#17]
I've removed a project from github, but the compile logs and output files still appear on sharelatex
(https://www.sharelatex.com/github/repos/szymtor/locfin), even after I've deleted my account on sharelatex.
Is there a way to remove the project from the sharelatex build service?

**Comment by jpallen** [comment]
The cloud compiler is a separate service from ShareLaTeX, but if you go to www.sharelatex.com/github and log inwith your GitHub account then there is an option to turn it off for each repo that is linked.

**Comment by szymtor** [comment]
The problem is that this repo is no longer visible there, as it has been removed from Github. In effect, I have no way of removing the built files and logs from the cloud compiler.

**Comment by szymtor** [comment]
I recreated a project with the same name in Github, containing a dummy tex file. The cloud compiler compiles the dummy file, and the project is again visible in the Cloud Compiler project listing (the logs of the previous builds are also visible, though). However, when I try to turn the project off, I get an "Internal Server Error". Is there some other way to remove the project from the cloud compiler?

**Comment by jpallen** [comment]
I've removed the project for you manually now.

**Comment by szymtor** [comment]
Thanks a lot. (I believe the issue is not resolved in general, though.)

**Comment by szymtor** [comment]
I just noticed – the previous builds are still visible. Could you please remove them as well?

**Comment by jpallen** [comment]
Done. I agree that there is still an open issue here. I will create a new clean issue for this.

**Comment by haoyun** [comment]
I am facing to the same problem. Hope it will be solved soon.
