### ISSUE TITLE
Problems with compiler. Not showing output.pdf

### ISSUE THREAD

**Issue by FavioVazquez** [sharelatex/github-latex-ci#25]
I haven't been able to view the compiled pdf's from the github-latex-ci, I didn't have this problem before so I don't know what's happening. Attached you'll find the output.pdf of one of my .TeX files.

Thanks. Please answer.
 
![screenshot from 2015-09-12 23 28 12](https://cloud.githubusercontent.com/assets/10162068/9835232/fb8d7bf6-59a5-11e5-9a08-6ced6bfbf035.png)

**Comment by FavioVazquez** [comment]
I see that the problem was fixed. Closing the Issue.

Thanks.

**Comment by henryoswald** [comment]
Yep it was a new security based header we added on which broke it.
