### ISSUE TITLE
Multiple Branch Handling

### ISSUE THREAD

**Issue by srizzling** [sharelatex/github-latex-ci#3]
Awesome Service btw. Been looking for a good workflow for git, latex and sharing the outputs to my supervisors. This seems to be easiest solution so far!

I have a few questions that I am unsure about:

Does the CI handle multiple branches of repo? For example, my intended workflow is to create have a release branch, that CI builds off, and another branch for my own work that regularly commit to but doesn't trigger the CI build? I haven't tried any of this yet but you think it would be possible?

**Comment by McSonk** [comment]
Isn't there yet a solution to this issue?

**Comment by henryoswald** [comment]
Github latex ci has been closed down for a few months now. Maybe you are looking at github sync in the editor?
