### ISSUE TITLE
GitHub autoconfigured webhook shows HTTP 403 error

### ISSUE THREAD

**Issue by dettmering** [sharelatex/github-latex-ci#31]
I added my dettmering/thesis-template repo to ShareLaTeX CI. It builds perfectly when clicking the build button, however the autoconfigured webhook gets a 403 error and the build isn't started after a commit. Does anybody else have this problem? It would be awesome to have this working!

**Comment by opomuc** [comment]
Yes, we are facing the same error since May, I think. Not sure what could cause it...
